In [102]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [103]:
df = pd.read_csv("alzheimers_disease_data.csv")

In [105]:
df.head(3)


PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0       4751   73       0          0               2  22.927749        0   
1       4752   89       0          0               0  26.827681        0   
2       4753   73       0          3               1  17.795882        0   

   AlcoholConsumption  PhysicalActivity  DietQuality  ...  MemoryComplaints  \
0           13.297218          6.327112     1.347214  ...                 0   
1            4.542524          7.619885     0.518767  ...                 0   
2           19.555085          7.844988     1.826335  ...                 0   

   BehavioralProblems       ADL  Confusion  Disorientation  \
0                   0  1.725883          0               0   
1                   0  2.592424          0               0   
2                   0  7.119548          0               1   

   PersonalityChanges  DifficultyCompletingTasks  Forgetfulness  Diagnosis  \
0                   0                          1              0          0   
1                   0                          0              1          0   
2                   0                          1              0          0   

   DoctorInCharge  
0             NaN  
1             NaN  
2             NaN  

[3 rows x 35 columns]

In [124]:
df = df.apply(pd.to_numeric, errors='coerce')

In [125]:
X = df.drop(columns=['Age']).values # replace 'Diagnosis' with your target column name
y = df['Diagnosis'].values # replace 'Diagnosis' with your target column name

In [126]:
print(x)


[73 89 73 ... 77 78 72]


In [127]:
print(y)

[0 0 0 ... 1 1 0]


In [146]:
df = df.dropna()

In [147]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [148]:

from sklearn import metrics

In [149]:
df = df.dropna()

In [157]:
model = GaussianNB()


In [151]:
df = df.dropna()


In [152]:
x_test[0:10]

array([[5.91000000e+03, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        2.63414569e+01, 0.00000000e+00, 1.77938656e+01, 1.01608725e+00,
        5.70803159e+00, 9.32501826e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.76000000e+02, 7.70000000e+01, 2.10949036e+02, 5.81105106e+01,
        9.66818499e+01, 2.06733352e+02, 1.44886407e+01, 7.30785083e+00,
        0.00000000e+00, 0.00000000e+00, 6.80070284e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00,            nan],
       [6.57300000e+03, 0.00000000e+00, 1.00000000e+00, 2.00000000e+00,
        3.09980336e+01, 1.00000000e+00, 4.84816494e+00, 3.77784640e-01,
        3.36739424e+00, 7.87298541e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.76000000e+02, 1.16000000e+02, 2.90195810e+02, 1.06740682e+02,
        9.62300836e+01,

In [153]:
y_test[0:10]


array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [155]:
df = df.dropna()

In [156]:
ml.fit(x_train,y_train)

ValueError: Input X contains NaN.
GaussianNB does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values